// Generated by https://quicktype.io

export interface Keyword {
  name: string;
  datatype?: DatatypeEnum;
  description: string;
  type: TypeEnum;
  example?: string;
  parameters?: Parameter[];
}

export enum DatatypeEnum {
  Boolean = "boolean",
  Expression = "expression",
  Float = "float",
  Integer = "integer",
  Null = "null",
  Object = "object",
  Set = "set",
  String = "string",
}

export interface Parameter {
  name: string;
  description?: string;
  type?: DatatypeEnum;
  default?: number | null | string;
  max?: number;
  min?: number;
}

export enum TypeEnum {
  Constant = "constant",
  Declaration = "declaration",
  Function = "function",
  Keyword = "keyword",
  Type = "type",
}
